<?php

namespace App\Support;

/**
 * Loads hand-authored format-guardrail scenarios for senior_laravel_dev (James Mitchell).
 *
 * Source of truth: scripts/extension-benchmark/answer-format-guardrails-scenarios.json
 * (curated static JSON; not generated by template loops).
 */
class AnswerFormatGuardrailScenarioData
{
    /**
     * @return list<array<string, mixed>>
     */
    public static function scenarios(): array
    {
        $path = base_path('scripts/extension-benchmark/answer-format-guardrails-scenarios.json');

        if (! is_file($path)) {
            throw new \RuntimeException(
                'Missing answer-format-guardrails-scenarios.json. '
                .'Curate scenarios under scripts/extension-benchmark/answer-format-guardrails/scenarios/ '
                .'then run: php scripts/extension-benchmark/merge-answer-format-guardrails-scenarios.php'
            );
        }

        $scenarios = json_decode((string) file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);

        if (! is_array($scenarios) || $scenarios === []) {
            throw new \RuntimeException('answer-format-guardrails-scenarios.json is empty');
        }

        return $scenarios;
    }
}
